version: '3.8'

networks:
  user_microservice_network:
    driver: bridge
  microservices_network:
    driver: bridge
# external: true

volumes:
  dbdata:
    driver: local
  user_storage:
    driver: local

services:
  # =================================================================
  # USER MICROSERVICE
  # =================================================================

  user_app:
    build:
      context: .
      dockerfile: supervisor.dockerfile
    image: ${USER_IMAGE_NAME:-user-microservice}
    container_name: ${USER_CONTAINER_NAME:-user-app}
    restart: unless-stopped
    working_dir: /app
    ports:
      - "${USER_PORT:-8080}:80"
    volumes:
      - user_storage:/app/storage
    networks:
      - user_microservice_network
      - microservices_network
    depends_on:
      - db:
        condition: service_started
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - CACHE_DRIVER=${CACHE_DRIVER:-file} 
      - SESSION_DRIVER=${SESSION_DRIVER:-file}

  db:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME:-user-service}
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-user-db}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - user_microservice_network
    ports:
      - "${DB_PORT_EXTERNAL:-3307}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
