version: '3.8'

networks:
  user_microservice_network:
    driver: bridge
  microservices_network:
    external: true

volumes:
  dbdata:
    driver: local

services:
  # =================================================================
  # USER MICROSERVICE
  # =================================================================

  user_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${USER_IMAGE_NAME}
    container_name: ${USER_CONTAINER_NAME}
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - user_microservice_network
      - microservices_network
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - CACHE_DRIVER=${CACHE_DRIVER} 
      - SESSION_DRIVER=${SESSION_DRIVER}

  user_webserver:
    image: nginx:alpine
    container_name: ${USER_WEBSERVER_NAME}
    restart: unless-stopped
    ports:
      - "${USER_PORT}:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - user_microservice_network
    depends_on:
      - user_app

  # =================================================================
  # INFRASTRUCTURE SERVICES
  # =================================================================

  db:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - user_microservice_network
    ports:
      - "${DB_PORT_EXTERNAL}:3306"
