version: '3.8'

networks:
  user_microservice_network:
    driver: bridge
  microservices_network:
    external: true

volumes:
  dbdata:
    driver: local

services:
  # =================================================================
  # USER MICROSERVICE
  # =================================================================

  # Conteneur PHP-FPM pour le service utilisateur
  user_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-microservice
    container_name: user-microservice-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - user_microservice_network
      - microservices_network
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:Mxb7G//GzC9MYoJzjPg0pRNBGZXXLYTH6eZ1kbhFzzo=
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=user_microservice
      - DB_USERNAME=user
      - DB_PASSWORD=user
      - QUEUE_CONNECTION=rabbitmq
      - RABBITMQ_HOST=rabbitmq_server
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_VHOST=/
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file

  # Conteneur Nginx pour le service utilisateur
  user_webserver:
    image: nginx:alpine
    container_name: user-microservice-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - user_microservice_network
    depends_on:
      - user_app

  # =================================================================
  # INFRASTRUCTURE SERVICES
  # =================================================================

  # Base de données MySQL
  db:
    image: mysql:8.0
    container_name: user-microservice-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: user_microservice
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: user
      MYSQL_USER: user
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - user_microservice_network
    ports:
      - "3306:3306"

